# Generated by Django 2.2.6 on 2021-04-08 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dueño',
            fields=[
                ('Rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
                ('Nombre2', models.CharField(max_length=20)),
                ('Apellidop', models.CharField(max_length=20)),
                ('Apellidom', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=80)),
                ('Edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Tipo', models.CharField(max_length=8)),
                ('Amo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='redsocial.Dueño')),
            ],
        ),
    ]
