# Generated by Django 2.2.6 on 2021-04-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('Rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20)),
                ('Nombre2', models.CharField(max_length=20)),
                ('Apellidop', models.CharField(max_length=20)),
                ('Apellidom', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=80)),
                ('Contraseña', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=80)),
                ('Edad', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='dueño',
            name='Contraseña',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='dueño',
            name='Email',
            field=models.CharField(default='gmail', max_length=80),
        ),
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(default='C:/mascotas/mascotas/Apps/redsocial/static/images/fomdo.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='dueño',
            name='Apellidom',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dueño',
            name='Apellidop',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dueño',
            name='Direccion',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='dueño',
            name='Edad',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dueño',
            name='Nombre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dueño',
            name='Nombre2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
