# Generated by Django 2.2.6 on 2021-04-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocial', '0004_auto_20210420_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(default='C:/mascotas/mascotas/Apps/redsocial/fp/fondo.jpg', upload_to='C:/mascotas/mascotas/Apps/redsocial/fp'),
        ),
    ]
