# Generated by Django 3.2 on 2021-04-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocial', '0005_auto_20210420_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=20, null=True)),
                ('Apellidop', models.CharField(max_length=20, null=True)),
                ('Direccion', models.CharField(max_length=80, null=True)),
                ('Contraseña', models.CharField(max_length=40, null=True)),
                ('Email', models.CharField(default='gmail', max_length=80)),
                ('Edad', models.IntegerField(default=0, null=True)),
                ('Tipo_usuario', models.IntegerField(choices=[[0, 'dueño'], [1, 'veterinario']])),
            ],
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='Amo',
        ),
        migrations.DeleteModel(
            name='Veterinario',
        ),
        migrations.DeleteModel(
            name='Dueño',
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
    ]
