# Generated by Django 3.2 on 2021-04-24 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redsocial', '0006_auto_20210423_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Tipo', models.CharField(max_length=8)),
                ('foto', models.ImageField(default='C:/mascotas/mascotas/Apps/redsocial/fp/fondo.jpg', upload_to='C:/mascotas/mascotas/Apps/redsocial/fp')),
                ('Amo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='redsocial.usuario')),
            ],
        ),
    ]
