# Generated by Django 3.2 on 2021-05-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redsocial', '0007_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ImageField(null=True, upload_to='mascotas'),
        ),
    ]
