# Generated by Django 3.2 on 2021-05-02 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redsocial', '0009_auto_20210502_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('comentario', models.TextField(max_length=1000)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redsocial.usuario')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
