# Generated by Django 3.2 on 2021-05-03 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redsocial', '0011_auto_20210502_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='Nombre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='redsocial.usuario'),
        ),
    ]
