# Generated by Django 3.2 on 2021-05-03 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redsocial', '0012_alter_comentario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='Nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='redsocial.usuario'),
        ),
    ]
