# Generated by Django 3.1.2 on 2021-05-04 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redsocial', '0013_alter_comentario_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
