# Generated by Django 3.1.2 on 2021-05-04 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redsocial', '0014_delete_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coment',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, null=True)),
                ('comentario', models.TextField(max_length=1000, null=True)),
                ('rut_comentario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='redsocial.usuario')),
            ],
        ),
    ]
