# Generated by Django 3.1.2 on 2021-05-04 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redsocial', '0015_coment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coment',
            name='rut_comentario',
        ),
    ]
