# Generated by Django 3.1.2 on 2021-05-04 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redsocial', '0017_pruebamela'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coment',
        ),
        migrations.DeleteModel(
            name='Pruebamela',
        ),
    ]
